version: "3.8"
services:
  mysql:
    image: mysql:5
    ports:
      - '3306:3306'
    environment:
        - MYSQL_USER=mysqluser
        - MYSQL_PASSWORD=ThePassword
        - MYSQL_DATABASE=api_db
        - MYSQL_ROOT_PASSWORD=1234
